list = [2,1,3]
print("OG list",list)
list.append(4)
print("Appending 4", list)
list.sort()
print("Sorting ascending" ,list)
list.sort(reverse=True)
print("sorting decending", list)
list.reverse()
print("Reverse", list)
list.insert(0,4)
print("Insertig in list", list)
list.remove(1)
print("removing 1", list)
list.pop(0)
print("using pop at index 0", list)